### ISSUE TITLE
Feat: Dashboard permalinks

### ISSUE THREAD

**Issue by AndreMiras** [beefyfinance/beefy-v2#1326]
As someone suggested on Discord, it would be great to be able to create dashboard permalink so we could track the positions of a wallet without being connected.
https://discord.com/channels/755231190134554696/910580808723599501/1079833386882973817
I can also work on the feature myself if you guys are interested

**Comment by erenjaegar77** [comment]
is already implemented the only thing u need to do is add to the url  `?__view_as=address`
for eg: https://app.beefy.com/dashboard?__view_as=0x4aba01fb8e1f6bfe80c56deb367f19f35df0f4ae

**Comment by AndreMiras** [comment]
Awesome thanks! So we just miss to have the link showing somewhere, or is it already available?
